version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

defaults: &defaults
  working_directory: ~/project/socktrader
  docker:
    - image: socktrader/socktrader-ci

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: cp src/config.ts.dist src/config.ts
      - run: mkdir test_results
      - persist_to_workspace:
          root: ~/project
          paths:
            - socktrader

  test-mutation:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run stryker

  test-unit:
    <<: *defaults
    parallelism: 3
    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Run Jest tests using test splitting
          command: |
            TESTFILES=$(circleci tests glob "src/__tests__/**/*.spec.ts" | circleci tests split --split-by=timings)
            npm test $TESTFILES --ci --maxWorkers=2 --coverage

      - codecov/upload:
          file: 'test_results/**/*.json'

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
          destination: test_results

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-mutation:
          requires:
            - install
      - test-unit:
          requires:
            - install
