version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

defaults: &defaults
  working_directory: ~/project/socktrader
  docker:
    - image: circleci/node:10.16.3

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: cp src/config.ts.dist src/config.ts
      - persist_to_workspace:
          root: ~/project
          paths:
            - socktrader
            -
#  analyze-code:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: ~/project
#
#      - run:
#          name: Run sonar scanner
#          command: >-
#            sonar-scanner
#            -Dsonar.projectKey=SockTrader_SockTrader
#            -Dsonar.organization=socktrader
#            -Dsonar.host.url=https://sonarcloud.io
#            -Dsonar.login=$SONAR_LOGIN

  analyze-code:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project

      - run: >-
          sonar-scanner
          -Dsonar.projectKey=SockTrader_SockTrader
          -Dsonar.organization=socktrader
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_LOGIN

  test-mutation:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Run mutation testing
          command: npm run stryker

  test-unit:
    <<: *defaults
    parallelism: 3
    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Run Jest tests using test splitting
          command: |
            TESTFILES=$(circleci tests glob "src/__tests__/**/*.spec.ts" | circleci tests split --split-by=timings)
            npm test $TESTFILES

      - codecov/upload

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results/coverage/clover.xml
          destination: clover.xml

      - store_artifacts:
          path: test_results/coverage/coverage-final.json
          destination: coverage-final.json

      - store_artifacts:
          path: test_results/coverage/lcov.info
          destination: lcov.info

      - store_artifacts:
          path: test_results/jest/junit.xml
          destination: junit.xml

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install

      - test-mutation:
          requires:
            - install

      - test-unit:
          requires:
            - install

      - analyze-code:
          requires:
            - install
