name: Pull request

on:
    pull_request:
        types:
            - opened
            - synchronize

env:
    TZ: UTC
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup Node LTS
                uses: actions/setup-node@v3
                with:
                    node-version: 'lts/*'
                    cache: 'npm'

            -   name: Install dependencies
                run: |
                    env
                    npm ci

#            -   name: Set env vars for Nx affected
#                uses: mansagroup/nrwl-nx-action@v3
#                with:
#                    targets: build
#                    affected: 'true' # Defaults to true, therefore optional
#                uses: nrwl/nx-set-shas@v3
#                with:
#                    main-branch-name: 'master'
#                    last-successful-event: 'workflow_dispatch'
##                    last-successful-event: 'pull-request'

            -   name: Build, lint & test affected packages
                uses: mansagroup/nrwl-nx-action@v3
                with:
                    targets: build,lint,test
                    affected: 'true'

